### PR TITLE
add info for lightning talks

### PR DESCRIPTION
**Pull request by robertkowalski**
blogpost for tomorrow

### CODE REVIEW

**Comment by OleMchls** [comment]
Why w/o slides? I guess it's quite hard to showcase a project (code) without _any_ slides. Just tell them that they should send them to you in pdf format 1hrs in advance to the talk, so you can merge all of them into one file and have one big slidedeck on one pc, maybe even /w a presenter

**Comment by robertkowalski** [comment]
Good point! Currently the lightning talks will happen in the Foyer Area, but like at Reject.JS we will have no place for a projector for the lightning talks, but for the next Unconf we should rent the biggest room including a projector.

**Comment by OleMchls** [comment]
Alright. Maybe you can support the speakers with a whiteboard or a flipchars. which would be fun anyway to see them drawn or they also might prepare some drawnings :lipstick:

**Comment by ro-ka** [comment]
So, are we going to merge this? Looks fine to me!

**Pull request merged**
